# Конфигурация плагина RTP

cooldown-time: 15   # Время восстановления в секундах (по умолчанию 15 секунд)
world: "world"      # Название мира, в котором будут телепортироваться игроки
radius: 6000       # Радиус случайной телепортации (по умолчанию 100 блоков)
message-prefix: "[RTP]"

teleport-sound:
  enabled: true        # Установите false, если хотите отключить звук телепортации
  sound-type: "ENTITY_ENDERMAN_TELEPORT"  # Тип звука по умолчанию, измените при необходимости
  volume: 1.0          # Настройка громкости (0.0 - 1.0)
  pitch: 1.0           # Настройка высоты звука (0.0 - 2.0)
