# Конфигурация плагина RTP

cooldown-time: 15   # Время восстановления в секундах (по умолчанию 15 секунд)
wait-time: 5        # Время ожидания до телепортации (по умолчанию 5 секунд)
world: "world"      # Название мира, в котором будут телепортироваться игроки
radius: 6000        # Радиус случайной телепортации (по умолчанию 100 блоков)
message-prefix: "<gray>[<red>RTP</red>]</gray>"

teleport-sound:
  enabled: true        # Установите false, если хотите отключить звук телепортации
  sound-type: "entity.enderman.teleport"  # Тип звука по умолчанию, измените при необходимости
  volume: 1.0          # Настройка громкости (0.0 - 1.0)
  pitch: 1.0           # Настройка высоты звука (0.0 - 2.0)

# Чтобы не отображать сообщение замените его на ""
messages:
  config-reloaded: "<green>Конфигурация перезагружена."
  no-permissions: "<red>У вас нет прав для выполнения этой команды."
  only-player: "<red>Только игроки могут использовать эту команду."
  tp-already-active: "<red>У вас уже есть ожидающая телепортация!"
  cooldown-await: "<red>Вы должны подождать <yellow>{seconds}</yellow> секунд перед использованием этой команды снова."
  wait: "<yellow>Телепортация через <gold>{seconds}</gold> секунд... Не двигайтесь!"
  canceled: "<red>Телепортация отменена, потому что вы двигались!"
  success: "<green>Вы были телепортированы в случайное место!"

  titles:
    wait-title: "<yellow>Телепортация через"
    wait-subtitle: "<gold>{seconds}</gold> <yellow>секунд"
    teleported-title: "<green>Телепортирован"
    teleported-subtitle: "<gold>Координаты: X={x}, Z={z}"
